### ISSUE TITLE
Update to latest stable 1.0

### ISSUE THREAD

**Issue by almaudoh** [backdrop-contrib/smsframework#3]
The latest changes in the D7 1.0 stable branch needs to be ported over.

**Comment by docwilmot** [comment]
Thanks. It will be a while I suspect. 
I noticed you are the Drupal maintainer. Would be happy to have you listed as maintainer over here too, if you agree.

**Comment by almaudoh** [comment]
> Would be happy to have you listed as maintainer over here too, if you agree.

No problem, I'd be glad to do that.

> It will be a while I suspect.

I plan on a PR in a couple of days. I'm just trying to diff the two branches right now.

**Comment by docwilmot** [comment]
Great!
@klonos how do we add @almaudoh to the authors list?

**Comment by serundeputy** [comment]
@almaudoh thanks for your help and interest!

would you mind filing an applications for contrib membership; listing that you are applying for co-maintainership of `smsframework` (mention that you are the Drupal maintainer) here: https://github.com/backdrop-ops/contrib/issues

Mainly we need you to sign off on the agreement then we can get you into the contrib authors group!

----
The full details are in the README.md here: https://github.com/backdrop-ops/contrib

**Comment by almaudoh** [comment]
PR is [here](https://github.com/backdrop-contrib/smsframework/pull/4)

**Comment by docwilmot** [comment]
Merged without testing.
